### ISSUE TITLE
Adding participants to an event will cause a crash

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Calendar#76]
### Technical information
```
System.Exception: ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Property 'Participant' was not found in type 'Simplified.Ring2.Person' (or baseclass). Json property: 'EventPageParticipants.FullName'.
Version: 2.3.1.6981.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14006.
   at Starcounter.XSON.DataBindingHelper.GetMemberForBinding(Type dataType, String bindingName, Template template, Boolean throwException, Boolean excludeCodegenMembers) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Binding\DataBindingHelper.cs:line 156
   at Starcounter.XSON.DataBindingHelper.GetBindingPath(Type dataType, Object data, String bindingName, Template template, Boolean throwException, Boolean excludeCodegenMembers) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Binding\DataBindingHelper.cs:line 101
   at Starcounter.XSON.DataBindingHelper.SearchForBinding(Json parent, String bindingName, TValue template, Boolean throwException) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Binding\DataBindingHelper.cs:line 52
   at Starcounter.XSON.TemplateDelegateGenerator.GenerateBoundDelegates[T](Property`1 property, Json json) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 234
   at Starcounter.Templates.Property`1.GenerateBoundGetterAndSetter(Json parent) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 148
   at Starcounter.Templates.TValue.UseBinding(Json parent) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Templates\Foundation\TValue.cs:line 252
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 213
   at Starcounter.Json.SetBoundValuesInTuple() in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 432
   at Starcounter.Json.RetriableSetBoundValues(Boolean retryOnError) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 405
   at Starcounter.Json.<>c__DisplayClass129_0.<ScopeAndSetBoundValuesInTuple>b__0() in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 378
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
   at Starcounter.Templates.TObjArr.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Templates\TObjArr.cs:line 162
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 341
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 242
   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 217
   at Starcounter.Json.<>c__DisplayClass124_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 198
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 349
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 242
   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 217
   at Starcounter.Json.<>c__DisplayClass124_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 198
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 103
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 118
   at Starcounter.XSON.JsonMimeConverter.Convert(Json json, MimeType mimeType, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.XSON\Class Json\JsonMimeConverter.cs:line 52
   at Starcounter.Internal.ResourceMimeConverter.TryConvert(Request request, IResource resource, String mimeTypeStr, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 67
   at Starcounter.Internal.ResourceMimeConverter.Convert(Request request, Response response, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 46
   at Starcounter.Response.ConvertResource(Request req) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Response.cs:line 765
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Response.cs:line 821
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Request.cs:line 1243
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 819
Data {
IsRethrown=True
}
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14006
```
##### Starcounter version
2.3.1.6981

##### Involved apps' version
Calendar - Develop branch
SignIn - Develop branch

### Screenshot
![calendarcrash](https://user-images.githubusercontent.com/10708580/29404300-f31c3582-833a-11e7-89cb-bd2de1c92289.gif)

**Comment by Joltrix** [comment]
This issue was resolved by [this commit](https://github.com/StarcounterApps/Calendar/commit/31d28a4cece342527a74ed448a3be7647ef49976)
